name: 'Issue in Project'
description: 'A Github action that moves issues in/into projects'
branding:
  icon: layout
  color: orange
inputs:
  token:
    description: 'Github token used to access the github API. Assign from '
    required: true
outputs:
  version:
    description: 'The version number derived from the current git commit.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    token: ${{ inputs.token }}
  args:
  - ${{ inputs.token }}
  - ${{ inputs.body }}
